name: mass_qr
description: Scan Several QR Codes in Quick Succession.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file: ^6.1.4
  provider: ^6.0.3 # To store and subscribe to app state (scans list)
  mobile_scanner: ^3.3.0 # To scan QR codes
  path_provider: ^2.0.1 # To get a temp. directory to store the generated .txt file
  share: ^2.0.1 # To use the OS share sheet to share the aforementioned .txt file
  url_launcher: ^6.0.3 # To open various links
  vibration: ^1.7.3
  flutter_tts: ^3.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  http: ^0.13.6
  shared_preferences: ^2.1.1
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true
  assets:
    - assets/empty_state.png
    - assets/ca/

