// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshvcfScBKfjvac1koCQZL0fvGjUTnDeU',
    appId: '1:752638087202:android:5d8e2114f14c2a0bba7a7b',
    messagingSenderId: '752638087202',
    projectId: 'easeit-89226',
    databaseURL: 'https://easeit-89226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'easeit-89226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuhJdF13nOEUkVvdMd54g79I_Ar_fsIQg',
    appId: '1:752638087202:ios:988560829deaf9d4ba7a7b',
    messagingSenderId: '752638087202',
    projectId: 'easeit-89226',
    databaseURL: 'https://easeit-89226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'easeit-89226.appspot.com',
    iosClientId: '752638087202-lhj117lfr6d0vgec425pf9ss1dh1kmu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.easeIt',
  );
}
